# Generated by Django 3.2.5 on 2021-07-16 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_rider_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='last_name',
        ),
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='url',
            field=models.URLField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='first_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Admin_app.rider'),
        ),
    ]
