# Generated by Django 3.2.5 on 2021-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_ride_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Name',
            field=models.CharField(default='Name', max_length=128),
        ),
    ]
