# Generated by Django 3.2.5 on 2021-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0006_alter_ride_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='Name',
        ),
        migrations.AddField(
            model_name='ride',
            name='Number_of_rides',
            field=models.PositiveIntegerField(default=1, max_length=40),
        ),
    ]
