# Generated by Django 3.2.5 on 2021-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0007_auto_20210716_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='Number_of_rides',
        ),
    ]
