# Generated by Django 3.2.5 on 2021-07-16 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0008_remove_ride_number_of_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='DateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
