# Generated by Django 3.2.5 on 2021-07-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0009_driver_dateofbirth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driver',
        ),
        migrations.DeleteModel(
            name='ride',
        ),
        migrations.DeleteModel(
            name='rider',
        ),
    ]
