# Generated by Django 3.2.5 on 2021-07-17 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_app', '0010_auto_20210717_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('DateOfBirth', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=1, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Admin_app.rider')),
            ],
        ),
    ]
